### ISSUE TITLE
nose -> pytests?

### ISSUE THREAD

**Issue by Justin-J-Miller** [bowman-lab/enspara#223]
There was some discussion in issue #214 about switching from nose to another testing suite. At the time the consensus was to switch to pytest. Is this still the preference?

Happy to poke at this in the coming days if so!

**Comment by lgsmith** [comment]
I think the one that seems most popular is the one that we should target.
Nose doesn't seem to be maintained, and won't work with the most current
version of python, so we can of course differ doing something about this if
we want but it will eventually need to be addressed unless someone else
picks up nose. The 'Note to users
<https://www.cargurus.com/Cars/inventorylisting/viewDetailsFilterViewInventoryListing.action?shopperListingsSearch=110980067#listing=371781738/NONE/DEFAULT>'
section mentions reasonable alternatives.

**Comment by Justin-J-Miller** [comment]
This is a link to a wonderful 2005 Ferrari.Yes, nose is no longer being maintained. There is nose2 which is mostly the same with some exceptions. Pytest seems to mostly work on our existing tests from my quick foray this morning. On Apr 13, 2024, at 2:43 PM, lgsmith ***@***.***> wrote:﻿
I think the one that seems most popular is the one that we should target.

Nose doesn't seem to be maintained, and won't work with the most current

version of python, so we can of course differ doing something about this if

we want but it will eventually need to be addressed unless someone else

picks up nose. The 'Note to users

<https://www.cargurus.com/Cars/inventorylisting/viewDetailsFilterViewInventoryListing.action?shopperListingsSearch=110980067#listing=371781738/NONE/DEFAULT>'

section mentions reasonable alternatives.



On Sat, Apr 13, 2024 at 9:37 AM Justin Miller ***@***.***>

wrote:

**Comment by lgsmith** [comment]
That's good. I think when we talked about this originally I'd thought pytest looked better. I think it may have been because the [readme](https://github.com/nose-devs/nose2?tab=readme-ov-file#nose2-vs-pytest) on nose2's github makes it seem like that is their recommendation. Maybe you saw that as well?

**Comment by justinrporter** [comment]
On projects after enspara I have used pytest and found it to be a very nice library. For whatever that’s worth.Sent from my iPhoneOn Apr 14, 2024, at 4:24 PM, lgsmith ***@***.***> wrote:﻿
That's good. I think when we talked about this originally I'd thought pytest looked better. I think it may have been because the readme on nose2's github makes it seem like that is their recommendation. Maybe you saw that as well?
